### ISSUE TITLE
need new admin

### ISSUE THREAD

**Issue by MonkmanMH** [bcgov/WES-demographic-profile#8]
@stephanieyurchak ... can I ask you to please take this one over? Thanks

**Comment by stephanieyurchak** [comment]
BC Stats team has admin already. If you are concerned because of the repo mountie blast, I think it's pinging you as a contributor. Steph H opened a ticket https://github.com/bcgov/repomountie/issues/192. 

I'll start archiving some of these old projects. That should help :)
